# Generated by Django 5.1.7 on 2025-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('MODERN', 'Modern'), ('PASSER', 'Passer')], default='MODERN', max_length=20),
        ),
    ]
