# Generated by Django 5.1.7 on 2025-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0002_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CHECK', 'Paiement par chèque'), ('CARD', 'Carte bancaire'), ('PAYPAL', 'Paypal'), ('CASH', 'Paiement à la livraison')], default='CHECK', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
