# Generated by Django 5.1.7 on 2025-04-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0002_article_blogpost_comment_order_product_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='karma.blogpost'),
            preserve_default=False,
        ),
    ]
