# Generated by Django 5.1.7 on 2025-04-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0004_order_address_order_city_order_country_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
